[project]
name = "fastapi-vector-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.11",
    "pgvector>=0.3.6",
    "pydantic-settings>=2.8.1",
    "uvicorn>=0.34.0",
]
